# -*- coding: utf-8 -*-
"""DiabetesProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a3wjZvaYf1GLVPkxrkObJUIQGU-kqcSM

# Load Data

## Import Libraries
"""

# Import pandas, numpy, math and matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import statsmodels.api as sm

# seaborn is a data visualization library built on matplotlib
import seaborn as sns

# set the plotting style
sns.set_style("whitegrid")

"""## Load Diabetes Datasets

### Diabetes 130-US Hospitals for Years 1999-2008
"""

# Loading dataset
diabetic_UCI = pd.read_csv("https://raw.githubusercontent.com/data5100-group/diabetes-risk-analysis/main/data/diabetic_data.csv")

# Loading mapping
ids_mapping_UCI = pd.read_csv("https://raw.githubusercontent.com/data5100-group/diabetes-risk-analysis/main/data/IDS_mapping.csv")

"""### Comprehensive Diabetes Clinical Dataset"""

# Loading dataset
diabetes_kaggle = pd.read_csv("https://raw.githubusercontent.com/data5100-group/diabetes-risk-analysis/main/data/diabetes_dataset.csv")

"""## Understand the Data"""

diabetes_kaggle.info()

diabetic_UCI.info()

"""# Clean the Datasets

## Columns to Keep
"""

diabetic_UCI = diabetic_UCI[[
    # Identifiers: One patient number can have multiple encounter ids
   "encounter_id", "patient_nbr",

    # Demographics
    "race", "gender", "age",

    # Admission/Discharge info
    "admission_type_id", "discharge_disposition_id", "admission_source_id",

    # Hospital Stay/ Utilization
    "time_in_hospital", "num_medications",
    "number_outpatient", "number_emergency", "number_inpatient",

    # Diagnosis Codes
    "diag_1", "diag_2", "diag_3", "number_diagnoses",

    # Medication Information
    "metformin", "repaglinide", "nateglinide", "chlorpropamide", "glimepiride",
    "acetohexamide", "glipizide", "glyburide", "tolbutamide", "pioglitazone",
    "rosiglitazone", "acarbose", "miglitol", "troglitazone", "tolazamide", "examide",
    "citoglipton", "insulin", "glyburide-metformin", "glipizide-metformin", "glimepiride-pioglitazone",
    "metformin-rosiglitazone", "metformin-pioglitazone", "change", "diabetesMed",

    # Outcome
    "readmitted"
]]

diabetes_kaggle = diabetes_kaggle[[
    # Demographics
    "age", "gender", "race:AfricanAmerican", "race:Asian", "race:Caucasian", "race:Other",

    # Factors
    "hypertension", "heart_disease", "smoking_history", "bmi", "hbA1c_level", "blood_glucose_level",

    # Outcome
    "diabetes"
]]

"""## Recombine diabetic_UCI and ids_mapping_UCI"""

first, second = ids_mapping_UCI.columns[:2]

m = ids_mapping_UCI.copy()
m[first] = m[first].astype(str).str.strip()

SECS = ["admission_type_id", "discharge_disposition_id", "admission_source_id"]

# Mark section rows only where the cell equals a section name
m["section"] = m[first].where(m[first].isin(SECS)).ffill()

# The top block in the CSV admission_type_id has no explicit marker row,
# so fill any remaining NAs with the first section name.
m["section"] = m["section"].fillna("admission_type_id")

# Keep only the three sections we care about
m = m[m["section"].isin(SECS)].copy()

# Keep only numeric ID rows within each section
m["id_num"] = pd.to_numeric(m[first], errors="coerce")
m = m[m["id_num"].notna()].copy()
m["id_num"] = m["id_num"].astype(int)

# Build dicts per section
maps = {sec: dict(zip(g["id_num"], g[second])) for sec, g in m.groupby("section")}
print("Mapping sizes:", {k: len(v) for k, v in maps.items()})

# Replace codes in-place in the main dataframe
for col in SECS:
    mp = maps.get(col, {})
    diabetic_UCI[col] = (
        pd.to_numeric(diabetic_UCI[col], errors="coerce")
          .astype("Int64")
          .map(mp)
          .astype("string")
    )

# Rename Columns without "id"
diabetic_UCI = diabetic_UCI.rename(columns={
    "admission_type_id": "admission_type",
    "discharge_disposition_id": "discharge_disposition",
    "admission_source_id": "admission_source",
})

"""# Exporting CSVs"""

# Turn the cleaned datasets to CSVs
diabetic_UCI.to_csv(
    'diabetic_UCI',
    encoding='utf-8-sig',
    index=False
)

diabetes_kaggle.to_csv(
    'diabetes_kaggle',
    encoding='utf-8-sig',
    index=False
)

# Download datasets
from google.colab import files

files.download('diabetic_UCI')
files.download('diabetes_kaggle')

"""### Handling Missing Values"""

diabetic_UCI.head()

diabetes_kaggle.head()

diabetic_UCI.isnull().sum()

"""During the data cleaning process, we identified missing values in the following categorical variables:
- `admission_type`  5,291
- `discharge_disposition` | 3,691
- `admission_source`  6,781
"""

diabetes_kaggle.isnull().sum()

"""To handle missing values in the admission-related categorical variables,  
we filled all `NaN` entries with the placeholder `"Unknown"` instead of removing rows.  
This helps preserve data while still allowing models to treat missing categories distinctly.
"""

diabetic_UCI['admission_type'].fillna('Unknown', inplace=True)
diabetic_UCI['discharge_disposition'].fillna('Unknown', inplace=True)
diabetic_UCI['admission_source'].fillna('Unknown', inplace=True)

"""Since these columns represent categorical features describing patient admission details, dropping the rows would lead to unnecessary data loss. Therefore, we decided to fill the missing values with `"Unknown"` to preserve the dataset’s completeness."""

diabetic_UCI[['admission_type','discharge_disposition','admission_source']].isnull().sum()

diabetic_UCI.isnull().sum().sum()

diabetes_kaggle.isnull().sum().sum()

"""This confirms that all missing values have been successfully handled.
The dataset is now fully cleaned and ready for exploratory data analysis (EDA).

##  Exploratory Data Analysis – Diabetes Kaggle Dataset

The goal for this dataset is to explore which **demographic and clinical factors** are related  
to whether a person has diabetes (`diabetes = 1`) or not (`diabetes = 0`).
"""

sns.countplot(x='diabetes', data=diabetes_kaggle)
plt.title('Distribution of Diabetes Cases')
plt.xlabel('Diabetes Diagnosis')
plt.ylabel('Count')
plt.show()

"""The bar chart shows the distribution of diabetes cases in the dataset. Most of the individuals are labeled as 0 (non-diabetic), while only a small portion are labeled as 1 (diabetic). This indicates that the dataset is imbalanced, with far more non-diabetic cases than diabetic ones. Such imbalance should be considered during model training to avoid biased predictions toward the majority class.

### Categorical Variables vs. Diabetes
"""

categorical_cols = ['gender', 'smoking_history']

for col in categorical_cols:
    plt.figure(figsize=(6,4))
    sns.countplot(x=col, hue='diabetes', data=diabetes_kaggle)
    plt.title(f'{col} vs Diabetes Status')
    plt.xticks(rotation=30)
    plt.show()

"""The first chart compares gender vs. diabetes status. It shows that both males and females have a similar pattern most individuals are non-diabetic (0), while only a small portion are diabetic (1). The “Other” gender category has very few records, indicating limited data in that group.

The second chart compares smoking history vs. diabetes status. Most participants have either never smoked or have no information on smoking history. Across all categories, non-diabetic individuals dominate, but there are slightly more diabetes cases among those who are current or former smokers, suggesting a potential relationship between smoking habits and diabetes risk.

#### Correlation Heatmap

We first select only the numeric columns to avoid errors from categorical variables.  
Then we plot the correlation matrix to see relationships between continuous variables.
"""

# Select only numeric columns
numeric_data = diabetes_kaggle.select_dtypes(include=['int64', 'float64'])

# Compute correlation matrix
corr = numeric_data.corr()

# Plot the heatmap
plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap – Diabetes Kaggle Dataset')
plt.show()

"""Blood glucose level (0.42) and HbA1c level (0.40) have the strongest positive correlations with diabetes, meaning higher values of these measures are closely linked to diabetes presence.

BMI and hypertension show moderate positive correlations, suggesting that individuals with higher BMI or hypertension are more likely to have diabetes.

Heart disease has a weaker correlation with diabetes (0.17), indicating a smaller but noticeable relationship.

Race variables (African American, Asian, Caucasian, Other) show minimal or no correlation, suggesting that race does not play a strong role in predicting diabetes in this dataset.

## Exploratory Data Analysis – Diabetic UCI Dataset

The goal of this section is to understand which demographic, clinical, and treatment-related factors  
are associated with **hospital readmission** among diabetic patients.

#### Readmission Distribution
We start by checking how often patients are readmitted within 30 days, after 30 days, or not at all.
"""

sns.countplot(x='readmitted', data=diabetic_UCI,
              order=['NO', '>30', '<30'])
plt.title('Distribution of Hospital Readmission Status')
plt.xlabel('Readmission Category')
plt.ylabel('Number of Patients')
plt.show()

"""The bar chart illustrates the distribution of hospital readmission status among patients. The three categories represent:

NO – Patients who were not readmitted,

>30 – Patients readmitted after 30 days, and

<30 – Patients readmitted within 30 days.

Most patients were not readmitted, followed by those readmitted after 30 days, while readmission within 30 days is the least frequent. This suggests that short-term readmissions are relatively rare compared to long-term or no readmissions, which could indicate effective post-discharge care for most patients.

#### Demographic Overview
"""

plt.figure(figsize=(6,4))
sns.countplot(x='gender', hue='readmitted', data=diabetic_UCI,
              order=['Male','Female'])
plt.title('Gender vs Readmission')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x='race', hue='readmitted', data=diabetic_UCI)
plt.title('Race vs Readmission')
plt.xticks(rotation=45)
plt.show()

"""The first chart shows the relationship between gender and hospital readmission status. Both male and female patients have similar patterns most were not readmitted (NO), followed by those readmitted after 30 days (>30), and the fewest were readmitted within 30 days (<30). However, females have slightly higher counts across all categories, suggesting they represent a larger portion of the dataset.

The second chart presents race vs. readmission status. It shows that Caucasian patients make up the majority of cases across all readmission categories, followed by African American patients. Other racial groups (Asian, Hispanic, and Other) have comparatively fewer records. Across all races, the trend remains consistent most patients were not readmitted, while short-term readmissions (<30 days) are the least common.

Treatment Factors (Insulin and Medication Changes)
"""

plt.figure(figsize=(6,4))
sns.countplot(x='insulin', hue='readmitted', data=diabetic_UCI)
plt.title('Insulin Usage vs Readmission')
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='change', hue='readmitted', data=diabetic_UCI)
plt.title('Medication Change vs Readmission')
plt.show()

"""The first chart displays insulin usage vs. hospital readmission status. Patients who did not use insulin have the highest number of non-readmissions. Among insulin users, those with steady or increasing (Up) insulin levels show slightly higher readmission counts, which may indicate that patients requiring regular insulin management are more prone to readmission.

The second chart shows medication change vs. readmission status. Patients with no medication change represent the largest group, but those who experienced a change (Ch) have a relatively higher proportion of readmissions, especially within 30 days. This trend suggests that changes in medication treatment could be linked to unstable health conditions, leading to higher readmission risks.

Correlation Heatmap for Numeric Variables
"""

numeric_data = diabetic_UCI.select_dtypes(include=['int64', 'float64'])
corr = numeric_data.corr()

plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap – Diabetic UCI Dataset')
plt.show()

"""time_in_hospital and num_medications show a moderate positive correlation (0.47), suggesting that patients who stay longer in the hospital tend to receive more medications.

number_emergency and number_inpatient are positively correlated (0.27), meaning patients with more emergency visits often have more inpatient admissions.

number_diagnoses is weakly correlated with most other variables but shows small positive relationships with time_in_hospital, num_medications, and encounter_id, indicating that more diagnoses might slightly increase hospital time and medication count.

## Statistical and Predictive Modeling
According to our proposal, this section combines statistical testing and simple predictive modeling  
to identify significant predictors in both datasets and compare overlapping risk factors.

## Modeling Question

### Step 7: Modeling Question

Our modeling stage focuses on exploring two major aspects of diabetes care using both datasets.

**Part 1 – Kaggle Dataset (Clinical Factors):**  
Since demographic variables (such as age or gender) were not strong predictors in our earlier models,
we focus on more clinically relevant factors that directly influence diabetes risk.  
Our question is:  
**How do key clinical factors such as BMI, HbA1c level, hypertension, and heart disease relate to patients’ blood glucose levels?**  
We use multiple correlation analysis and linear regression models to identify which variables are most strongly associated with blood glucose level.

**Part 2 – UCI Dataset (Hospital Readmission Patterns):**  
In the hospital dataset, our question is:  
**Which clinical or hospital-related variables best predict whether a diabetic patient is readmitted within 30 days?**  
We explore relationships between variables such as time in hospital, number of medications, and number of lab procedures with readmission status to identify patterns that could inform hospital management and patient care.

Both parts together provide a comparative view of diabetes management, connecting
clinical health indicators with hospital outcomes.

Modeling Question (UCI Dataset)
In this section, we analyze the hospital dataset to understand factors related to readmission among diabetic patients.

Our goal is to identify which factors are associated with **longer hospital stays**,
which can increase the risk of **readmission** and reflect the overall management challenges
in diabetes care.

We focus on numeric variables that represent treatment intensity and hospital utilization:
- **num_medications**
- **number_inpatient**
- **number_emergency**
- **number_outpatient**
- **number_diagnoses**

These variables capture how frequently diabetic patients interact with the healthcare system
and how complex their treatment patterns are.  

We use multiple correlation analysis and multiple linear regression to explore
how these predictors relate to `time_in_hospital` and to highlight potential patterns
that may contribute to readmission among diabetic patients.

Correlation Analysis
"""

diabetic_UCI.columns

# Select numeric variables related to hospital and treatment factors
uci_correlation_vars = diabetic_UCI[['time_in_hospital',
                              'num_medications',
                              'number_inpatient',
                              'number_emergency',
                              'number_outpatient',
                              'number_diagnoses']]

# Calculate correlation matrix
uci_correlation = uci_corr_vars.corr()

# Display correlation matrix
uci_correlation

"""This correlation analysis is performed on patients who have already been diagnosed with diabetes.  
We explore how hospital and treatment-related factors are related to the length of hospital stay,
which can reflect the complexity of diabetes management.

We expect:
- time_in_hospital to have a positive correlation with num_medications and number_inpatient,
  since diabetic patients who require more medications or repeated admissions often have
  more severe or poorly controlled conditions.
- number_diagnoses may also be correlated with hospital stay, indicating multiple diabetes-related complications.

By analyzing these patterns among diabetic patients, we gain insight into the hospital care
factors that contribute to longer stays and potentially higher readmission risk.
"""

# Define predictors (X) and target (y)
X = diabetic_UCI[['num_medications', 'number_inpatient',
                  'number_emergency', 'number_outpatient',
                  'number_diagnoses']]
y = diabetic_UCI['time_in_hospital']

# Add constant term
X = sm.add_constant(X)

# Fit multiple linear regression model
uci_model = sm.OLS(y, X).fit()

# Display model summary
print(uci_model.summary())

"""This regression model explores how hospital and treatment-related factors
affect the length of hospital stay among diabetic patients.

- A positive coefficient for variables such as `num_medications`
  or `number_inpatient` indicates that patients taking more medications
  or having more inpatient visits tend to stay in the hospital longer.  
  This suggests higher disease complexity or less stable diabetes management.
- number_diagnoses may also contribute to longer stays,
  as diabetic patients often experience multiple comorbid conditions.
- The R² value indicates how much variation in hospital stay duration
  can be explained by these predictors.
- p-values < 0.05 identify which predictors are statistically significant contributors.
"""

